### ISSUE TITLE
Tesla Login don't work after move to template "tesla-command" (evcc 0.124.0)

### ISSUE THREAD

**Issue by dev-da77** [teslamotors/vehicle-command#165]
I updated my evcc.yaml according the changes on evcc 0.124.0 for my tesla:

```
vehicles:
- type: template
  template: tesla-command
  title: Tesla
  accessToken: <...>
  refreshToken: EU_<...>
  vin: <...>
  name: ev1
```

After: sudo systemctl restart evcc

I get:

```
[main  ] INFO 2024/02/04 22:39:24 evcc 0.124.0
[main  ] INFO 2024/02/04 22:39:24 using config file: /etc/evcc.yaml
[db    ] INFO 2024/02/04 22:39:24 using sqlite database: /root/.evcc/evcc.db
[mqtt  ] INFO 2024/02/04 22:39:24 connecting evcc-xxxxxxxxx at tcp://ha:1883
[mqtt  ] DEBUG 2024/02/04 22:39:24 tcp://ha:1883 connected
[main  ] ERROR 2024/02/04 22:39:26 creating vehicle ev1 failed: cannot create vehicle type 'template': cannot create vehicle type 'tesla-command': oauth2: "login_required" "Login required"
.Soc:     vehicle not available: cannot create vehicle type 'template': cannot create vehicle type 'tesla-command': oauth2: "login_required" "Login required"
Capacity: 0.0kWh
Features: [Offline]
```

Ideas?
